README.md

remove extra parentheses from readme

---

auth.ts
package.json
pnpm-lock.yaml

remove the last `@ts-ignore`
Incorporates the fix from https://github.com/nextauthjs/next-auth/commit/8fcd46b0fc5ea9c5418aca267a187b9f4da80a8d

chore: upgrade `next-auth`

---

app/actions.ts

check chats length before run kv.pipeline() otherwise get empty pipeline, we get this error when there is no chats in storage

clearChats

---

app/chat/[id]/page.tsx

- Fix a potential error in generating metadata title in chat page. 
- Improves app stability and user experience.
- #40

fix: Fix metadata title generation in chat pages

---

pnpm-lock.yaml

https://github.com/nextauthjs/next-auth/pull/7443/commits/179c08d45ba0ca63addeb807afd4ff572cfd5dc7
Spent two hours on this. <picture data-single-emoji=":upside_down_cry:" title=":upside_down_cry:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/upside_down_cry/feeefabbbcaa4067.png" alt=":upside_down_cry:" align="absmiddle"></picture>
The `x-forwarded-proto` header returns `https`, but `URL#protocol` returns `https:`.
This made our cookies not being properly set in secure (HTTPS) environments, causing various issues when deployed.
Fixes #28
You can run `pnpm up @auth/nextjs` in your own project to apply this fix.

chore: upgrade `@auth/nextjs`

---

README.md

The `AUTH_SECRET` env var is missing from the Vercel deploy button, which cases the chatbot auth to fail. Saw this happen twice, both at a hackathon and helping a friend with it yesterday.

Added missing required env var in vercel deploy

---

auth.ts

Github auth provider doesn't return back a `picture` prop like Google. instead, it returns `avatar_url`.
<details>
<summary>Here is an instance of the data returned</summary>
```json
{
"login": "A7med3bdulBaset",
"id": 000000,
"node_id": "00000000000000000",
"avatar_url": "https://avatars.githubusercontent.com/u/82659015?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/A7med3bdulBaset",
"html_url": "https://github.com/A7med3bdulBaset",
"followers_url": "https://api.github.com/users/A7med3bdulBaset/followers",
"following_url": "https://api.github.com/users/A7med3bdulBaset/following{/other_user}",
"gists_url": "https://api.github.com/users/A7med3bdulBaset/gists{/gist_id}",
"starred_url": "https://api.github.com/users/A7med3bdulBaset/starred{/owner}{/repo}",
"subscriptions_url": …
```

fix: User Image returned from auth provider

---

README.md

Update docs to include mention of Cohere support. To my understanding the `ai` library already supports the Cohere SDK and developers can switch the provider as such. Thanks in advance.

Update docs to include Cohere support

---

components/ui/codeblock.tsx

Currently, selecting the code block will also select the line number, making the copied content look like this:
```
1const response = new Response('Auth Required.', {
2  status: 401,
3  headers: {
4    'WWW-authenticate': 'Basic realm="Secure Area"'
5  }
6});
```
This PR tries to fix that.
(Yes I know the copy button exists but say people might want to select only part of the code block.)
**Disclaimer:** I never tested this code – this PR was made on a whim entirely using GitHub UI, because I faced this problem while I was using chat.vercel.ai. I only hope that this works – sorry for that 😅

Disable selection on code block line numbers

---

components/chat.tsx

Disable default scroll behavior in router.push() when creating a new chat.

prevent scrolling to top on chat creation

---

app/actions.ts
auth.ts

This pull request addresses an issue in the removeChat function where an 'Unauthorized' error was being incorrectly thrown. The problem was due to a type mismatch during the user ID comparison.
In the existing code, the user ID from the session (a string) was being compared to the user ID from the chat (a number). This strict inequality check would fail due to the different types, even if the user IDs were the same.
The fix involves converting both IDs to strings before comparing them. This ensures that the comparison is done between two strings, and it will work correctly even if the IDs are originally of different types.
With this fix, the 'Unauthorized' error will only be thrown when it should be, i.e., when the user ID of the session does not match the user ID of the chat.

Fix type mismatch in removeChat function

---

scripts/seed.mjs

I failed to run `pnpm seed` due to this syntax error
```
> node -r dotenv/config ./scripts/seed.mjs
Error seeding users: error: syntax error at or near "salt"
```

Fix SQL syntax error

---

app/layout.tsx

The template crashes when cloning, even after `vc env pull`, since `VERCEL_URL` is set to an empty string when pulling env var.
1. Deploy https://vercel.com/templates/next.js/nextjs-ai-chatbot 
1. Clone the repo locally 
1. vc link
1. vc env pull
1. pnpm i
1. pnpm dev

fix crash when cloning locally

---

app/(chat)/page.tsx

The import path for the getMissingKeys function was updated from '../actions' to '@/app/actions' to align with the project's import conventions and improve code clarity.
resolves issue #319 
before:
```
import { getMissingKeys } from '../actions'
```
after:
```
import { getMissingKeys } from '@/app/actions'
```

refactor: Update import path for getMissingKeys

---

app/(chat)/chat/[id]/page.tsx
app/actions.ts
components/sidebar-list.tsx

Previously, `getChats` and `getChat` wasn't checking if the request's session user id matched the chats that were being fetched. This patches that behavior by adding an explicit check.

Check session user id before performing action

---

.env.example

change kv database to Vercel Blob Store

chore: fix typo in .env.example

---

components/console.tsx

Previously, the console outputs persisted even after the block was closed. This pull request ensures the console is cleared when the block is closed.

feat: clear console outputs when closing block

---

components/console.tsx
components/run-code-button.tsx

Previously, the block content would remain empty after closing and reopening – this pull requests fixes this behavior.

fix: prevent empty code execution outputs after remount

---

components/multimodal-input.tsx

Previously, on large inputs, the height would persist after submission – this pull request ensures the height is reset to its initial height.

fix: reset input height on submission

---

components/console.tsx

Previously, long outputs would overflow the console window out of bounds – this pull requests prevents that from happening and ensures the contents remain inside the console.

fix: lock horizontal scroll for console

---

components/block.tsx
components/code-editor.tsx
components/document-preview.tsx

Previously when using the code editor, updates and saves would reset the cursor position – this pull requests fixes this behavior and persists the current cursor position.

fix: preserve cursor position on code editor saves

---

components/block.tsx

This pull request removes the left border around canvas when resized to accommodate smaller screens.

fix: hide left border around canvas when resized

---

blocks/code.tsx
blocks/image.tsx
blocks/text.tsx
components/block-actions.tsx
components/block.tsx
components/create-block.tsx

This pull request restores the loading states and image outputs during code execution of the code block.

fix: restore code block loading states

---

blocks/actions.ts
components/block.tsx

This pull request fixes the block's initialize function being called several times during stream.

fix: run block initialize fn only once

---

components/message.tsx
package.json
pnpm-lock.yaml

feat: refactor to use parts

---

artifacts/code/server.ts

This PR fixes a bug in the `onUpdateDocument` function where the model name was incorrectly set to 'artifacts-model' instead of 'artifact-model'. 
- Updated `myProvider.languageModel('artifacts-model')` to `myProvider.languageModel('artifact-model')`.
This change ensures the correct model is used, preventing errors in document updates.

Fix incorrect model name in onUpdateDocument function

---

app/(chat)/api/chat/route.ts
app/(chat)/api/document/route.ts
app/(chat)/api/vote/route.ts
components/chat.tsx
playwright.config.ts

This pull request adds an explicit auth check for both `/chat` and `/vote` routes.

fix: check chat/vote ownership during actions

---

components/multimodal-input.tsx

This was implemented before, but regressed: https://github.com/vercel/ai-chatbot/pull/63 
Without this, typing in CJK language is difficult: https://github.com/vercel/ai-chatbot/issues/48

Fix (again): send message on Enter keypress only when not in input method mode

---

components/chat.tsx

This pull request only begins polling votes after reaching a minimum messages count (2) in a chat conversation.

fix: poll votes after min message count

---

components/icons.tsx

This took me way too long to figure out, but the plus icon was off-center with respect to its viewbox. I hand-edited the path to center it on 8,8... how it should be. To see the difference, just pull up the production deployment side-by-side with the preview deployment and inspect the plus icon in the "new chat" button.

chore: Center the plus icon so I don't die

---

app/(chat)/api/chat/route.ts
lib/ai/prompts.ts
lib/ai/tools/get-weather.ts

This pull request uses the geolocation api from `@vercel/functions` to get the lat/lng of the request to use for weather tool instead of relying on the language model guess it.

feat: get lat/lng from geolocation api

---

app/(chat)/api/document/route.ts
components/version-footer.tsx
package.json

This pull request replaces `PATCH` method with `DELETE` method when deleting document versions through the `api/document` endpoint

refactor: replace patch with delete for /api/document

---

lib/ai/models.test.ts
playwright.config.ts
tests/e2e/artifacts.test.ts
tests/e2e/auth.setup.ts
tests/e2e/auth.test.ts
tests/e2e/chat.test.ts
tests/e2e/reasoning.setup.ts
tests/e2e/reasoning.test.ts

This pull requests does the following:
Fixes #935

chore: organize tests and tweak stream delays

---

lib/ai/prompts.ts
package.json

This pull request prevents including backticks to code snippets.

fix: do not include backticks for code blocks

---

components/message.tsx
package.json

This pull request fixes an alignment issue that was cause by not rendering the attachments component even when there was none.
Before:
After:

fix: conditionally render attachments component

---

lib/db/helpers/01-core-to-parts.ts
package.json

This pull request fixes the following behaviors in the migration script:

chore: tweak migration script to handle message order

---

app/(chat)/api/chat/route.ts
app/(chat)/api/chat/schema.ts
app/(chat)/chat/[id]/page.tsx
app/(chat)/page.tsx
components/artifact.tsx
components/chat.tsx
components/multimodal-input.tsx
components/sidebar-history-item.tsx
components/suggested-actions.tsx
components/visibility-selector.tsx
hooks/use-chat-visibility.ts
lib/db/queries.ts
package.json
tests/pages/chat.ts
tests/routes/chat.test.ts

This pull request supports setting visibility type (public/private) on initial chat creation. Previously this was failing.

fix: support setting visibility on initial chat creation

---

.env.example
app/(chat)/api/chat/route.ts
package.json

This pull request falls back to using normal stream if resumable streams is not supported either due to missing keys or redis initialization failures.

feat: fallback to normal stream if cannot resume stream

---

components/message.tsx
components/multimodal-input.tsx

chat interface, adjusted input design, message alignment, and improved visual consistency
- redesigned input box with modern rounded-3xl styling and better proportions
- implemented fixed 72px height that remains consistent during all interactions
- improved dark mode theming with sidebar-matching background colors
- enhanced send button with proper circular design and grey styling
- fixed sparkles icon positioning to align properly with message text baseline
- eliminated layout shifts between "hmm..." thinking state and actual ai responses
- positioned thinking message to appear exactly where response will show
- improved user message alignment for better visual balance

fix(ui): adjust input boxes + background

---

app/globals.css
components/app-sidebar.tsx
components/chat-header.tsx
components/chat.tsx
components/elements/actions.tsx
components/elements/conversation.tsx
components/elements/reasoning.tsx
components/greeting.tsx
components/message-actions.tsx
components/message.tsx
components/messages.tsx
components/multimodal-input.tsx
components/sidebar-toggle.tsx
components/ui/sidebar.tsx
hooks/use-messages.tsx
hooks/use-scroll-to-bottom.tsx

the chatbot had issues with user messages appearing on the left instead of right, edit buttons shifting layout when hovered, poor mobile scrolling, and ugly scrollbars. needed to fix message alignment and make the interface work better on mobile devices.
- fixed user messages to appear on right side with blue bubbles
- made edit icon appear on hover without shifting message position  
- added smooth mobile scrolling and touch optimizations
- created minimal 6px scrollbars that match the theme
- fixed accessibility issues with sidebar and tooltips
- made input box smaller and cleaner (44px height)
- moved scroll-to-bottom button above input instead of covering it
tested on mobile safari, android chrome, and desktop browsers. all message alignment works correctly, edit icons don't shift …

ui: mobile chatbot improvements

---

components/chat-header.tsx

Removes Grok as a required integration when setting up a new project from the Vercel deploy button.

Remove Grok integration requirement

---

vercel-template.json

Adds `vercel-template.json` for specifying configuration at `vercel.com/templates`
We'd like to move more template configuration into GitHub as the "source of truth"

Add `vercel-template.json`

---

README.md
components/chat-header.tsx

Updated deployment URLs from legacy clone-based flow to use Vercel templates.
In this repo, we reference Vercel deployment URLs directly, and these use the legacy clone-based deployment flow which make the update process tedious as these values have to be updated whenever the template requirements change. 
Replace all instances of the clone flow invoke URL with the Vercel templates URL so it becomes the canonical source of truth. This is a stop-gap until we can switch away from using our CMS as the source of truth in favor of a file at the root of the repo that is used as a template.
Work has started on that here: #1193 
This PR updates all usages to ensure users are directed to the correct, maintained deployment flow. It also removes the need for updates to code when the template …

[docs] Update deploy URLs to point to `/templates/next.js/nextjs-ai-chatbot`

---

package.json
pnpm-lock.yaml

This pull request updates the `streamdown` package from version 1.2.0 to 1.3.0 and makes corresponding updates to the lockfile. The update brings in new dependencies and updates several related packages, ensuring compatibility and potentially adding new features or bug fixes.
Dependency updates related to `streamdown`:
* Upgraded `streamdown` dependency in `package.json` from version 1.2.0 to 1.3.0.
* Updated `pnpm-lock.yaml` to reflect the new `streamdown` version and its dependencies, including the addition of `rehype-raw@7.0.0`, `hast-util-raw@9.1.0`, and `hast-util-to-parse5@8.0.0`. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL231-R232) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3408-R3419) …

Bump Streamdown
