vercel/ai-chatbot

- .env.example
- README.md
We need to add a few environment variables to our .env file.
Here is how our .env file should look with these new variables:
```bash
KV_URL=
KV_REST_API_URL=
KV_REST_API_TOKEN=
KV_REST_API_READ_ONLY_TOKEN=
```
> Add KV Database Environment Variables to .env.example file

- components/chat-message-actions.tsx
- components/ui/codeblock.tsx
- lib/hooks/use-copy-to-clipboard.tsx
Reduce ineffective triggering of the clipboard
> fix: Reduce ineffective triggering of the clipboard

- tailwind.config.js
Fix repeated tailwind extend fontFamily
> fix: Repeated tailwind extend fontFamily

- .env.example
- README.md
Ref: https://github.com/vercel-labs/ai-chatbot/pull/80#discussion_r1244067642
Could not find a good place for this in the README.md, so just updated the comments in the `.env.example`. Let me know if you think it's sufficient.
> docs: clarify `next-auth` instructions

- components/chat-share-dialog.tsx
- components/header.tsx
This PR removes unused imports.
> Remove unused imports

- lib/hooks/use-streamable-text.ts
console.log is spamming the console with the streaming response
> remove console.log from streamable response

- lib/chat/actions.tsx
- package.json
- pnpm-lock.yaml
> Use streamUI instead of render

- lib/chat/actions.tsx
- Add done for onSetAIState
- Use guard clause pattern
Closes #412, thanks @jb-dev1
> Save to db on final ai state update

- components/custom/auth-form.tsx
- components/custom/navbar.tsx
- Use next/form where possible
> Next.js 15 fast follows

- app/(chat)/layout.tsx
- components/custom/multimodal-input.tsx
- next.config.ts
- package.json
- pnpm-lock.yaml
> Persist input text in local storage

- components/custom/chat.tsx
- components/custom/message.tsx
Reverts vercel/ai-chatbot#492
Causes canvas to close after generation ends
> Revert "Push route state on generation finish"

- lib/db/queries.ts
> Correctly import server-only

- components/block-actions.tsx
- components/block-close-button.tsx
- components/block-messages.tsx
- components/block-stream-handler.tsx
- components/block.tsx
- components/chat-header.tsx
- components/chat.tsx
- components/document.tsx
- components/message.tsx
- components/messages.tsx
- components/multimodal-input.tsx
- components/sidebar-history.tsx
- components/suggested-actions.tsx
- components/toolbar.tsx
- package.json
- pnpm-lock.yaml
memoize the following components to minimize unintended re-renders:
> fix: memoize components and improve performance

- components/sidebar-history.tsx
- components/visibility-selector.tsx
update other instances of check icon that was renamed in #596
> chore: update icons after rename

- components/suggested-actions.tsx
Updates suggested actions to have examples of normal text generation, text block, code block, and tool calling with generative user interfaces
> chore: update suggested actions

- app/(chat)/api/chat/route.ts
- app/(chat)/chat/[id]/page.tsx
- components/app-sidebar.tsx
- components/document-preview.tsx
- components/message.tsx
- components/multimodal-input.tsx
- components/sidebar-history.tsx
- components/suggested-actions.tsx
- components/toolbar.tsx
- lib/ai/prompts.ts
> fix: tweak styles

- components/messages.tsx
> fix: add condition to messages memoization ruleset

- components/data-stream-handler.tsx
closes #682 
Suggestion stream part was removed in PR #637. This pull request restores handling the suggestion stream part.
> fix: handle suggestion stream parts

- app/(chat)/api/chat/route.ts
- components/block-actions.tsx
- components/block.tsx
- components/data-stream-handler.tsx
- components/document-preview.tsx
- components/document-skeleton.tsx
- components/image-editor.tsx
- components/toolbar.tsx
- hooks/use-multimodal-copy-to-clipboard.ts
- lib/ai/index.ts
- lib/db/schema.ts
- package.json
- pnpm-lock.yaml
This pull request adds a new image block type
> feat: add image block type

- app/(chat)/api/chat/route.ts
- lib/ai/tools/create-document.ts
- lib/ai/tools/update-document.ts
- package.json
- pnpm-lock.yaml
This pull request applied stream transformation to reduce the choppiness of the stream using [`smoothStream`](https://sdk.vercel.ai/docs/ai-sdk-core/generating-text#smoothing-streams).
> feat: add smooth stream

- app/(chat)/api/chat/route.ts
- lib/ai/prompts.ts
This pull request switches prompts and available tools based on the selected chat model.
> feat: switch prompts based on selected chat model

- blocks/image/server.ts
- components/chat.tsx
- components/messages.tsx
- lib/ai/models.ts
This pull request uses the correct image model id and cleans up stale code.
> fix: use correct image model name

- lib/db/schema.ts
This pull request makes the enum in the schema definition dynamically populated.
> refactor: make block kind enum dynamic in schema

- app/(chat)/api/chat/route.ts
- package.json
- pnpm-lock.yaml
This pull request handles client disconnects during a generation by using `consumeStream` ([docs](https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-message-persistence#handling-client-disconnects)).
> feat: handle client disconnects

- components/chat.tsx
- components/create-artifact.tsx
- components/data-stream-handler.tsx
- components/toolbar.tsx
- next-env.d.ts
- package.json
- pnpm-lock.yaml
This pull requests bumps versions of next and ai packages to the latest versions.
> chore: bump versions

- components/artifact-messages.tsx
- components/artifact.tsx
- components/chat.tsx
- components/message.tsx
- components/messages.tsx
- components/multimodal-input.tsx
- components/toolbar.tsx
- lib/ai/models.test.ts
- tests/pages/chat.ts
- tests/reasoning.test.ts
This pull request replaces `isLoading` (which is now deprecated) with `status`.
> refactor: replace isLoading with status

- .env.example
- .vscode/settings.json
- README.md
- app/(chat)/api/chat/route.ts
- components/multimodal-input.tsx
- components/suggested-actions.tsx
- components/toolbar.tsx
- docs/02-update-models.md
- lib/ai/providers.ts
- package.json
- pnpm-lock.yaml
This pull request updates the models to use providers that are available on the vercel marketplace.
> feat: update providers

- package.json
This pull request versions the template at 3.0.0
> chore: version template to 3.0.0

- app/(chat)/api/document/route.ts
- package.json
This pull request verifies document ownership before appending a new version. 
Addresses #892
> fix: verify document ownership before appending version

- app/(chat)/api/document/route.ts
- lib/db/queries.ts
- package.json
- playwright.config.ts
- tests/auth-helper.ts
- tests/routes/document.test.ts
This pull request adds tests for `/api/document`.
Addresses #892
> feat: add tests for /api/document

- app/(chat)/api/chat/route.ts
- lib/db/queries.ts
- package.json
- playwright.config.ts
- tests/fixtures.ts
- tests/prompts/basic.ts
- tests/prompts/routes.ts
- tests/routes/chat.test.ts
- tests/routes/document.test.ts
This pull request adds tests for `/api/chat` route.
> feat: add tests for /api/chat

- lib/constants.ts
- lib/db/queries.ts
- lib/db/utils.ts
- lib/utils.ts
- package.json
This pull request moves functions that are referenced by `queries.ts` to `db/utils.ts`. This is in reponse to an error the prevented server compiled functions to be defined in `lib/utils.ts` that was used by client components.
> chore: move server functions to db/utils

- components/chat.tsx
- package.json
- tests/e2e/chat.test.ts
- tests/pages/chat.ts
This pull request adds support for creating messages from url query (ported from the live branch).
> feat: support message creation from url query

- app/(chat)/api/chat/route.ts
- lib/ai/prompts.ts
- package.json
- pnpm-lock.yaml
This pull request adds support for appending request hints to the system prompt using `@vercel/functions`. For instance, it is useful for figuring out the user's geo location and respond to prompts about the weather at their location.
> feat: support appending request hints to prompt

- .eslintrc.json
> fix: eslint error when use path alias

- lib/db/schema.ts
- package.json
This pull request updates the the link to migration guide docs present in the codebase.
Continuation from #987
> chore: update links to migration docs

- app/(chat)/api/chat/route.ts
- app/(chat)/api/document/route.ts
- app/(chat)/api/history/route.ts
- app/(chat)/api/suggestions/route.ts
- app/(chat)/api/vote/route.ts
- components/chat.tsx
- lib/db/queries.ts
- lib/errors.ts
- lib/utils.ts
- package.json
- tests/e2e/session.test.ts
- tests/routes/chat.test.ts
- tests/routes/document.test.ts
This pull request improves the management of creating errors with meaningful codes and messages, using the `ChatSDKError` class.
> feat: improve error messages

- components/sheet-editor.tsx
- components/sidebar-user-nav.tsx
This fixes issues caused by checking the value of theme from useTheme instead of resolvedTheme. The former can be "light", "dark", or "system" whereas the latter can only be "light" or "dark"
> fix: use resolved theme value

- app/(chat)/api/chat/route.ts
> fix: message ordering

- components/elements/response.tsx
fixed mermaid diagram processing error that was incorrectly interpreting code blocks as diagrams
- overrode code component in ai elements response to prevent mermaid processing
- code blocks now render as plain code instead of being interpreted as potential diagrams
- eliminates "no diagram type detected" errors when displaying programming code
> fix mermaid processing error in code blocks

- README.md
- components/multimodal-input.tsx
reasoning model does not allow images so file button is disabled in this instance
> fix: reasoning model does not allow images

- app/(chat)/api/chat/route.ts
- components/chat.tsx
- lib/errors.ts
When using this template before activating AI Gateway, requests will fail. 
This PR introduces a new error type for this error (`bad_request:add_card`). It will render a modal when this specific error is encountered.
Note: error type and activation link is hard coded.
> fix: add dialog for vercel ai gateway activation

- app/(auth)/login/page.tsx
- app/(auth)/register/page.tsx
Reverts vercel/ai-chatbot#1199
> Revert "fix(auth): registration flow infinite loop and session state sync"
